// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4rocBQQ8teXkuNBCn07qZfYBspsrFeHw',
    appId: '1:910553012369:android:b8d6f48ba5b5ef7a9f4730',
    messagingSenderId: '910553012369',
    projectId: 'chitchat-c9a2e',
    storageBucket: 'chitchat-c9a2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj6CBKefsCZBF8hJ045d6Gb8D52ZBxY8o',
    appId: '1:910553012369:ios:5f629a6efb1f8f9b9f4730',
    messagingSenderId: '910553012369',
    projectId: 'chitchat-c9a2e',
    storageBucket: 'chitchat-c9a2e.appspot.com',
    androidClientId: '910553012369-n38skc3ps7rptbi6ppb496gk4qflb5d7.apps.googleusercontent.com',
    iosClientId: '910553012369-bpjgu4uq5gmevea4fbte2lq5v6g4hu1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.chitChat',
  );
}
